FROM maven:3.9.4-eclipse-temurin-17 as build
WORKDIR /app
COPY . .
FROM maven:3.9.4-eclipse-temurin-17
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
